language: csharp
solution: CocNET.sln
install:
- nuget restore CocNET.sln
- nuget install NUnit.ConsolerRunner -Version 3.6.1 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Debug CocNET.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit-console.exe ./CocNET.Test/bin/Debug/CocNET.Test.dll